# Generated by Django 5.2 on 2025-07-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='opportunityapplication',
            name='cv',
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='cv_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
