# Generated by Django 5.2 on 2025-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_market', '0002_remove_message_file_remove_opportunityapplication_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
    ]
