# Generated by Django 5.2 on 2025-07-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image_project_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
