# Generated by Django 5.2 on 2025-07-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_tasksubmission_file_tasksubmission_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfile',
            name='file',
        ),
        migrations.AddField(
            model_name='roomfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
