# Generated by Django 5.2 on 2025-07-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_roomfile_file_roomfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
