app = "eduvia-ai"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 50
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/healthcheck/"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[env]
  DISABLE_COLLECTSTATIC = "0"
  DEBUG = "True"  # مؤقتًا للتجربة
  SESSION_COOKIE_SECURE = "True"
  CSRF_COOKIE_SECURE = "True"
  SECURE_SSL_REDIRECT = "True"

[mounts]
  source = "eduvia_data"
  destination = "/data"
