# Generated by Django 5.2 on 2026-05-15 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_options_alter_courseenrollment_options_and_more'),
        ('marketplace', '0005_merge_0003_alter_enrollment_student_related_name_0004_enrollmentcode_schema_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(choices=[('paymob', 'Paymob')], default='paymob', max_length=16)),
                ('transaction_id', models.CharField(max_length=128, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coursepurchase',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursepurchase',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='revenueshare',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payoutapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payoutapproval',
            name='withdrawal_request',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='wallet',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='uq_marketplace_enrollment',
        ),
        migrations.RenameField(
            model_name='instructorwallet',
            old_name='available_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='revenueshare',
            old_name='gross_revenue',
            new_name='instructor_amount',
        ),
        migrations.RenameField(
            model_name='revenueshare',
            old_name='instructor_earnings',
            new_name='platform_amount',
        ),
        migrations.RemoveField(
            model_name='instructorwallet',
            name='pending_balance',
        ),
        migrations.RemoveField(
            model_name='instructorwallet',
            name='withdrawn_balance',
        ),
        migrations.RemoveField(
            model_name='revenueshare',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='tx_type',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_v2', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('paymob', 'Paymob'), ('enrollment_code', 'Enrollment Code'), ('admin', 'Admin')], max_length=24),
        ),
        migrations.AlterField(
            model_name='enrollmentcode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_enrollment_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructorwallet',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_active_student_course_enrollment'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueshare',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_share', to='marketplace.coursepayment'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='marketplace.coursepayment'),
        ),
        migrations.DeleteModel(
            name='CoursePurchase',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='PayoutApproval',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
