# Generated by Django 5.2 on 2026-05-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='marketplace.coursepayment'),
        ),
    ]
