# Generated by Django 5.2 on 2025-06-30 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meet_link', models.URLField(blank=True, help_text='Google Meet link for the live session', max_length=500)),
                ('session_image', models.ImageField(blank=True, help_text='Upload an image for the session', null=True, upload_to='media/live_session_images/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='live_sessions_participated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='Upload the recorded video after the live session', upload_to='media/live_recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='workshops.livesession')),
            ],
        ),
    ]
