# Generated by Django 5.2 on 2025-07-10 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverecording',
            name='video_file',
            field=models.URLField(help_text='enter the recorded url video after the live session', max_length=500),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'courses_profile__role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='session_image',
            field=models.URLField(blank=True, default='', help_text='Enter the image url (example: PostImage)', max_length=500),
            preserve_default=False,
        ),
    ]
