# Generated by Django 5.2 on 2025-07-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_liverecording_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='session_image',
            field=models.URLField(blank=True, help_text='Enter the image url (example: PostImage)', max_length=500, null=True),
        ),
    ]
