# Generated by Django 5.2 on 2025-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_post_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
