# Generated by Django 5.2 on 2025-08-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_duration',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('six_months', 'Six Months'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
