# Generated by Django 5.2 on 2025-07-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
