# Generated by Django 5.2 on 2025-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userprofile_full_name_alter_userprofile_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
