# Generated by Django 5.2 on 2025-07-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_userprofile_full_name_alter_userprofile_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='unlocked',
        ),
    ]
