# Generated by Django 5.2 on 2025-08-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_video_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium'), ('instructor_plan', 'Instructor Plan')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='videofile',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='video_files/'),
        ),
    ]
