# Generated by Django 5.2 on 2025-11-11 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_userprofile_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('english', 'English'), ('math', 'Math')], default='programming', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Enter a clear and descriptive course title.', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long.')]),
        ),
    ]
