# Generated by Django 5.2 on 2025-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_options_remove_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
