# Generated by Django 5.2 on 2025-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_video_unlocked_video_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier (auto-generated)', max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL for video', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=10, help_text='Duration in minutes'),
        ),
    ]
