# Generated by Django 5.2 on 2026-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_slug_unicode_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='video',
            name='unlocked',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='task',
            name='questions',
            field=models.JSONField(default=list, help_text="List of questions as dictionaries with 'question', 'options', and 'correct_answer'"),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=10, help_text='Duration of the video in minutes (to be entered manually by the instructor)'),
        ),
    ]
