# Generated by Django 5.2 on 2026-05-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_userprofile_subscription_end_date_and_more'),
    ]

    operations = [
        # الحقول subscription_end_date و subscription_plan
        # لم تكن موجودة في قاعدة البيانات فعلياً، لذا لا يلزم حذفها.
    ]