# Generated by Django 5.2 on 2026-05-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lesson_task_system_and_course_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessontask',
            name='external_url',
            field=models.URLField(blank=True, help_text='For external_link tasks — URL students must visit.'),
        ),
        migrations.AlterField(
            model_name='lessontask',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=70, help_text='Minimum % (0–100) required to pass.'),
        ),
        migrations.AlterField(
            model_name='lessontask',
            name='questions',
            field=models.JSONField(default=list, help_text='MCQ: [{"question":"...","options":[...],"correct_answer":"..."}]. Essay: [{"question":"..."}]. File/Link: leave [].'),
        ),
        migrations.AlterField(
            model_name='lessontasksubmission',
            name='score',
            field=models.FloatField(default=0.0, help_text='Percentage 0–100'),
        ),
    ]
