# Generated by Django 5.2 on 2026-05-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_userprofile_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_plan',
        ),
    ]
